# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('meta_title', models.CharField(max_length=1024)),
                ('meta_h1', models.CharField(max_length=1024)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('meta_title', models.CharField(max_length=1024)),
                ('meta_h1', models.CharField(max_length=1024)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('img', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField()),
                ('link', models.CharField(max_length=1024)),
                ('enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'category_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('phone', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
            ],
            options={
                'db_table': 'product_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'product_parameter_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('enabled', models.IntegerField()),
                ('comment_admin', models.TextField()),
            ],
            options={
                'db_table': 'product_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=65)),


            ],
            options={
                'db_table': 'product_sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStockBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
            options={
                'db_table': 'product_stock_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('adress', models.TextField()),
                ('enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('role', models.CharField(max_length=1024)),
                ('reg_date', models.DateTimeField()),
                ('name', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
                ('adress', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Data.ProductArticle')),
                ('name', models.CharField(max_length=1024)),
                ('meta_title', models.CharField(max_length=1024)),
                ('meta_h1', models.CharField(max_length=1024)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('description_full', models.TextField()),
                ('link', models.CharField(max_length=1024)),
                ('enabled', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('views', models.IntegerField()),
                ('article', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Data.Product')),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'product_rate',
                'managed': False,
            },
        ),
    ]
