# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Data.Product')),
            ],
        ),
    ]
