# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('meta_title', models.CharField(max_length=1024)),
                ('meta_h1', models.CharField(max_length=1024)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=1024)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
