# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('phone', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('count', models.IntegerField(default=1)),
                ('Full_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('count', models.IntegerField(default=1)),
                ('Full_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('is_active_basket', models.BooleanField()),
            ],
            options={
                'db_table': 'productinbasket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
    ]
